name: GitHub Actions Build and Deploy Blog
on:
  push:
    branches:
      - blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x] 
    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
    
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} # 版本
    
    - name: 3. install hexo...
      run: |
        npm i hexo-cli --save -g
        npm i hexo-wordcount --save -g
        npm i hexo-deployer-git --save -g
        npm i hexo-generator-archive --save -g
        npm i hexo-generator-category --save -g
        npm i hexo-generator-index --save -g
        npm i hexo-generator-feed --save -g
        npm i hexo-generator-search --save -g
        npm i hexo-generator-tag --save -g
        npm i hexo-permalink-pinyin --save -g
        npm i hexo-prism-plugin --save -g
        npm i hexo-renderer-ejs --save -g
        npm i hexo-renderer-marked --save -g
        npm i hexo-renderer-stylus --save -g
        npm i hexo-filter-github-emojis --save -g
        npm install

    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g

    - name: 5. Build and Deploy
      uses: y4code/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY: holddie/holddie.github.io 
        BRANCH: master  
        PUBLISH_DIR: ./
